### ISSUE TITLE
preparing clipart dataset problem and multigpu training 

### ISSUE THREAD

**Issue by lerndeep** [harsh-99/SCL#11]
![image](https://user-images.githubusercontent.com/55526377/76608198-9932eb80-6558-11ea-8fe0-3c486ce8608f.png)
 After training started, I faced those errors but I have no idea why I got those errors. could you explain?
I tried to train network with multi-GPU by using CUDA_VISIBLE_DEVICES=0,1 but it is just using GPU 0, why?

**Comment by harsh-99** [comment]
Hi, 
About the dataset, I have never faced such kind of problem. you can try to see some standard problem which occurs with the dataset, when training for object detection.
I have not written the code to accommodate multiple GPUs.
Thanks

**Comment by lerndeep** [comment]
I understand how this problem exists. if Xmax is lower than Xmin this problem will exist. I have one question about source data, is it possible to train network without any object labels? I am a training network for defect detection with my own dataset but I also want to train network without defect data(normal data with no defect region) for understanding the normality of data. do you have any suggestions about training?

**Comment by harsh-99** [comment]
I think for that case, you might have to alter the architecture. First, a classifier which detects if there is any defect or not. If there is a defect then you do detection of the defected part. This way you will be able to feed both kinds of images while training.
