### ISSUE TITLE
Experimental details

### ISSUE THREAD

**Issue by jizefeng0810** [harsh-99/SCL#12]
When performing the task K2C, only the car class is used when training the KITTI dataset? Or do all classes train and only show the AP of the car class in the final result?

**Comment by harsh-99** [comment]
This is incorporated in the code. You have to take whole dataset, however the models will be trained only on the class "Car".  Please check the below link.
https://github.com/harsh-99/SCL/blob/master/lib/datasets/kitti_car.py#L48
