### ISSUE TITLE
visualization of features from PASCAL to Clipart

### ISSUE THREAD

**Issue by lerndeep** [harsh-99/SCL#13]
I have question about visualizing data after domain adaptation training. how you visualized data using tsne after training? could you provide idea how can I visualize source and target data after training?

**Comment by harsh-99** [comment]
I have used the feature after Conv Block 3, using max pooling converted them to size of (1,1). Then saved the features in a text file, which have embedding of both source and target domain. After that I have used tsne code for python from the below link.
https://lvdmaaten.github.io/tsne/
