### ISSUE TITLE
Can this method be used as unsupervised object detection, if yes then how to do object detection on unlabelled target domain data

### ISSUE THREAD

**Issue by nileshmis** [harsh-99/SCL#15]
Hi,

How can we use this method as unsupervised domain adaptation with object detection and run object detection on unlabelled target domain data like clipart

**Comment by harsh-99** [comment]
Hey,
How would you train object detector if you don't have labels for Source domain? I didn't get your question clearly, could please elaborate?

**Comment by nileshmis** [comment]
Hi,
I have labels in source domain, but not in target domain i.e. pascal dataset (source domain) has labels and clipart dataset(target domain) don't have labels, then in this case "Will this implementation work and Can I train my model using SCL code"??

**Comment by harsh-99** [comment]
Yeah, of course, that would work. That is domain adaptation. You need source domain labels, you need target domain data (unlabelled) and then you adapt your model from source domain to target domain.

**Comment by nileshmis** [comment]
hey harsh-99,
I want to do object detection on clipart(target domain) dataset and i am training my model using pascal dataset as (source domain) and clipart dataset as (target domain) both have annotation.xml, but what if clipart dataset(target domain) don't have annotation.xml, how to do object detection on clipart sample that don't have annotation.xml, i tried to remove/comment annotation.xml code but i am getting error, how to solve or approach to this issue,Thanks in advance.
