### ISSUE TITLE
Can I run this Solution in real time or without the need to train the target data

### ISSUE THREAD

**Issue by nmski** [harsh-99/SCL#17]
Hi,

I want to train this solution in real-time by capturing images and run algorithm on top of it, but also i don't want to train target data, can this be done?

Thanks,
Nilesh

**Comment by harsh-99** [comment]
Hi,
Probably I don't get your question clearly. But if you don't have any target data then how is it a problem of domain adaptation?
Please mention the question more clearly.

Regards,
Harsh

**Comment by nmski** [comment]
Hi harsh,

Sorry, if i was not clear before , i just wanted to confirm that can i test the model on new test dataset/images which has not been trained/run as target domain data (during training trainval_scl.py). i.e., I want to test the model with respect to new dataset which has not been trained/run with target domain data.
basically i want to run testnet_scl.py on new dataset that is not trained as target domain dataset using trainval_scl.py but that is similar to target domain dataset and run object detection on this new dataset.

Thanks,
Nilesh

**Comment by harsh-99** [comment]
Yes of course you can do that. Dataset setting you can have according to your choice, the expected results would be according to that. 

Regards,
Harsh
