### ISSUE TITLE
About cityscape and foggy dataset

### ISSUE THREAD

**Issue by ddghost** [harsh-99/SCL#18]
Hi,

I run the dataset preparation code in DA-Faster RCNN, but it can only generate trainval.txt. I just want to know how to create the train.txt? 

Besides, the dataset preparation code only generate a folder contains both cityscape and foggy images. However, it seems that I need two different folder path from the lib/datasets/config_dataset.py. Could you explain how to generate this two folders?

**Comment by harsh-99** [comment]
Hi,

In that data prep code, they have merged the source and target list file names for training and written in one file trainval.txt, instead you will have to separate them i.e. first try process just source images and make it's corresponding train.txt, test.txt. Similarly do it for the target images also.

**Comment by ddghost** [comment]
Thanks for your reply.  

Could you provide me the train.txt and test.txt of cityscape and foggy?  It will be better to check if I generate the right data.

**Comment by harsh-99** [comment]
Hi, 
This is my train.txt and test.txt for source dataset.

[test.txt](https://github.com/harsh-99/SCL/files/5372031/test.txt)
[train.txt](https://github.com/harsh-99/SCL/files/5372033/train.txt)
