### ISSUE TITLE
About sim10k dataset

### ISSUE THREAD

**Issue by ddghost** [harsh-99/SCL#23]
Hi, when I download the sim10k from the website, I can only get the trainval.txt. How do you split it into train.txt and val.txt?

**Comment by Qianyu666** [comment]
Hello, did you address this issue? How do you split the SIM10K dataset into train.txt and val.txt?

**Comment by qianyuzqy** [comment]
@ddghost Hello, did you address this issue? How do you split the SIM10K dataset into train.txt and val.txt?

**Comment by ddghost** [comment]
@Qianyu666 No, I used other dataset.
