### ISSUE TITLE
How do I use cityscape and foggy cityscapes datasets? 

### ISSUE THREAD

**Issue by jizefeng0810** [harsh-99/SCL#5]
Hello, author. How do I use cityscape and foggy cityscapes datasets? Da fasterrcnn generates the JSON format file of coco type. Could you talk about how to generate the dataset format used by the code? Thank you very much.

**Comment by harsh-99** [comment]
Hi, 
As mentioned in ReadMe file we have used prepare_data.m for DA faster RCNN repository. It generates data in the required VOC format only. I assume that you might have used some other codes. Please provide them here if problem persists.

**Comment by jizefeng0810** [comment]
Sorry, I have a final exam recently, so I haven't replied to you. You are right! I have used some other codes. Now, I use prepare_data.m for DA faster RCNN repository, but it have error when I run code. Have you ever seen this error? The error information:
`Unable to perform assignment because the left and right sides have a different number of elements.

Error in prepare_data (line 103)
        gt.category(i_inst) = lb_filter(inst_lb);`

**Comment by harsh-99** [comment]
Hi, 
I have never faced this type of error. If you have downloaded the dataset from official website then this problem should not be there. However I will try to see if I can debug or understand the issue.

**Comment by jizefeng0810** [comment]
I solved this problem, my dataset is not right.
